# This is a basic workflow that is manually triggered

name: url to guilded drive v114514

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      videourl:
        description: 'Video URL: '
        default: ''
        required: true
      spaceclear:
        description: 'clear space? '
        default: ''
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ruantics:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout Codes
      uses: actions/checkout@v2

    - name: Pre-processing
      run: |
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf /opt/ghc
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf "/usr/local/share/boost"
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -lh
        wget "${{ github.event.inputs.videourl }}" -O "luminethonk.sh" > /dev/null 2> /dev/null

    - name: Download Antics and Reuploading
      continue-on-error: true
      run: |
        bash luminethonk.sh
  ruantics2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [ruantics]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout Codes
      uses: actions/checkout@v2

    - name: Pre-processing
      run: |
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf /opt/ghc
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf "/usr/local/share/boost"
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -lh
        wget "${{ github.event.inputs.videourl }}" -O "luminethonk.sh" > /dev/null 2> /dev/null

    - name: Download Antics and Reuploading
      continue-on-error: true
      run: |
        bash luminethonk.sh
  ruantics3:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [ruantics, ruantics2]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout Codes
      uses: actions/checkout@v2

    - name: Pre-processing
      run: |
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf /opt/ghc
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf "/usr/local/share/boost"
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -lh
        wget "${{ github.event.inputs.videourl }}" -O "luminethonk.sh" > /dev/null 2> /dev/null

    - name: Download Antics and Reuploading
      continue-on-error: true
      run: |
        bash luminethonk.sh
  ruantics4:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [ruantics, ruantics2, ruantics3]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout Codes
      uses: actions/checkout@v2

    - name: Pre-processing
      run: |
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf /opt/ghc
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf "/usr/local/share/boost"
        [ "${{ github.event.inputs.spaceclear }}" ] && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -lh
        wget "${{ github.event.inputs.videourl }}" -O "luminethonk.sh" > /dev/null 2> /dev/null

    - name: Download Antics and Reuploading
      continue-on-error: true
      run: |
        bash luminethonk.sh
